#!/usr/bin/env python3
"""Materializer for linkshort → renders the brain as flat wiki pages under brain/.

Pipeline (no LLM; deterministic summaries):
  EXTRACT     tools/extract.py -> nodes/edges (functions, flags, edges)
  INVALIDATE  diff vs the last published graph by per-symbol source_sha
  RENDER      wiki-flat projections:
                Home.md          index (RECOMPUTED)
                <module>.md      per-subsystem entity pages (RECOMPUTED)
                Features.md      feature -> flag map / kill-switch view (RECOMPUTED)
                Changelog.md     APPEND-ONLY history
  PUBLISH     brain/  (then tools/publish_wiki.sh copies these into the .wiki.git)

Usage: python3 materializer/materialize.py
"""
from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# The brain's persistent store. Locally this is ./brain; in CI it is the cloned
# wiki repo (set via BRAIN_DIR), so the previous graph + append-only changelog
# survive between runs. This is the brain living *outside* the source tree (ADR 0007).
BRAIN = Path(os.environ["BRAIN_DIR"]) if os.environ.get("BRAIN_DIR") else REPO / "brain"
SCHEMA_VERSION = 1
EXTRACTOR = ["python3", "tools/extract.py"]


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "nogit"


def extract() -> tuple[list[dict], list[dict]]:
    out = subprocess.run(EXTRACTOR, cwd=REPO, capture_output=True, text=True, check=True).stdout
    data = json.loads(out[out.find("{"):])
    return data["nodes"], data["edges"]


def page_name(subsystem: str) -> str:
    return subsystem.split(":")[-1]  # "python:shorten" -> "shorten"


def load_json(name: str, default):
    f = BRAIN / name
    return json.loads(f.read_text()) if f.exists() else default


def diff_nodes(old: list[dict], new: list[dict]) -> dict:
    o, n = {x["id"]: x for x in old}, {x["id"]: x for x in new}
    return {
        "added": [n[i] for i in n if i not in o],
        "removed": [o[i] for i in o if i not in n],
        "changed": [n[i] for i in n if i in o
                    and n[i]["provenance"]["source_sha"] != o[i]["provenance"]["source_sha"]],
    }


def short_intent(node: dict) -> str:
    return (node.get("intent") or "_(no intent)_").split(". ")[0].strip()


# ---- renderers (wiki-flat markdown) ---------------------------------------

def render(nodes: list[dict], edges: list[dict], sha: str, stamp: str) -> dict:
    entities = [n for n in nodes if n["type"] in ("function", "method")]
    flags = [n for n in nodes if n["type"] == "flag"]
    gated_by: dict[str, list[str]] = {}
    for e in edges:
        if e["type"] == "gated-by":
            gated_by.setdefault(e["to"], []).append(e["from"])

    subsystems: dict[str, list[dict]] = {}
    for n in entities:
        subsystems.setdefault(n["subsystem"], []).append(n)

    foot = f"\n\n---\n_Generated from `{sha}` · {stamp}. Derived projection — do not edit; regenerated by the materializer._\n"

    # per-subsystem entity pages
    for sub, ns in subsystems.items():
        lines = [f"# {page_name(sub)}", ""]
        for n in sorted(ns, key=lambda x: x["title"]):
            f = n["facts"]
            lines += [f"## `{n['title']}` · {n['type']}", "", n.get("intent") or "_(no intent)_", ""]
            lines.append(f"- **params:** {', '.join(f['params']) or '—'}")
            lines.append(f"- **returns:** {f['returns'] or '—'}")
            lines.append(f"- **raises:** {', '.join(f['raises']) or '—'}")
            if f.get("flag"):
                lines.append(f"- **feature:** `{f.get('feature') or '—'}` — gated by `{f['flag']}` (see [Features](Features))")
            p = n["provenance"]
            lines.append(f"- _source:_ `{p['source_path']}` · `{p['source_sha']}` · {p['status']}")
            lines.append("")
        (BRAIN / f"{page_name(sub)}.md").write_text("\n".join(lines) + foot)

    # Features.md — feature -> flag map / kill-switch view
    flines = ["# Features", "",
              "Each feature is toggled by a flag in `flags.yml`. To turn a feature on/off, flip its flag.", ""]
    for fl in sorted(flags, key=lambda x: x["title"]):
        ff = fl["facts"]
        ents = gated_by.get(fl["id"], [])
        gates = ", ".join("`" + e.split("#")[-1] + "`" for e in ents) or "—"
        flines += [f"## `{fl['title']}`", "", fl.get("intent") or "_(no description)_", ""]
        flines.append(f"- **default:** `{ff.get('default')}`")
        flines.append(f"- **owner:** {ff.get('owner') or '—'}")
        flines.append(f"- **gates:** {gates}")
        flines.append(f"- **to toggle:** flip `{fl['title']}` (currently defaults to `{ff.get('default')}`)")
        flines.append("")
    (BRAIN / "Features.md").write_text("\n".join(flines) + foot)

    # Home.md — index
    hlines = ["# linkshort — knowledge wiki", "",
              "_Auto-generated from the source on every merge to `main`. This is a derived"
              " read model; edits here are overwritten._", "", "## Modules", ""]
    for sub in sorted(subsystems):
        hlines.append(f"- [{page_name(sub)}]({page_name(sub)}) — {len(subsystems[sub])} functions")
    hlines += ["", "## Operations", "", "- [Features](Features) — feature flags & how to toggle them",
               "- [Changelog](Changelog) — what changed, and why", ""]
    (BRAIN / "Home.md").write_text("\n".join(hlines) + foot)

    return subsystems


def append_changelog(delta: dict, seq: int, sha: str, stamp: str) -> None:
    f = BRAIN / "Changelog.md"
    header = "# Changelog\n\n_Append-only. Newest first._\n"
    prior = ""
    if f.exists():
        body = f.read_text()
        prior = body.split("\n", 3)[-1] if body.startswith("# Changelog") else body
    entry = [f"\n## #{seq} · `{sha}` · {stamp}", ""]
    for n in sorted(delta["added"], key=lambda x: x["id"]):
        entry.append(f"- ➕ `{n['id']}` — {short_intent(n)}")
    for n in sorted(delta["changed"], key=lambda x: x["id"]):
        entry.append(f"- ✏️ `{n['id']}` — {short_intent(n)}")
    for n in sorted(delta["removed"], key=lambda x: x["id"]):
        entry.append(f"- ➖ `{n['id']}`")
    entry.append("")
    f.write_text(header + "\n".join(entry) + ("\n" + prior if prior.strip() else ""))


def main() -> int:
    sha, stamp = git_sha(), datetime.now().isoformat(timespec="seconds")
    print(f"materialize @ {sha}")
    nodes, edges = extract()
    print(f"  · extracted {len(nodes)} nodes, {len(edges)} edges")

    prev = load_json("graph.json", {"nodes": []})
    delta = diff_nodes(prev["nodes"], nodes)
    changed = bool(delta["added"] or delta["removed"] or delta["changed"])
    first_run = not (BRAIN / "graph.json").exists()
    print(f"  · delta: +{len(delta['added'])} ~{len(delta['changed'])} -{len(delta['removed'])}")

    BRAIN.mkdir(exist_ok=True)
    subsystems = render(nodes, edges, sha, stamp)

    state = load_json("state.json", {"seq": 0})
    if changed or first_run:
        state["seq"] += 1
        append_changelog(delta, state["seq"], sha, stamp)
        print(f"  · changelog entry #{state['seq']} appended")
    else:
        print("  · no changes (idempotent)")

    (BRAIN / "graph.json").write_text(json.dumps(
        {"schema_version": SCHEMA_VERSION, "generated_from_sha": sha,
         "node_count": len(nodes), "nodes": nodes, "edges": edges}, indent=2))
    state.update({"schema_version": SCHEMA_VERSION, "last_sha": sha, "node_count": len(nodes)})
    (BRAIN / "state.json").write_text(json.dumps(state, indent=2))
    print(f"  → brain/  ({len(subsystems)} module pages + Features + Changelog + Home)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
